#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const memoryDir = path.join(repoRoot, '.memory');
const contextPath = path.join(memoryDir, 'context.md');
const statePath = path.join(memoryDir, 'state.json');

const SECTION_HEADERS = {
  decisions: '## Key Decisions',
  mistakes: '## Wall of Shame',
  todos: '## Active Tasks',
  completed: '## Completed Tasks',
  history: '## History',
};

const PLACEHOLDER_LINES = new Set([
  '<!-- Entries are added via: project-memory log --mistake "description" -->',
  '<!-- Current work items. Added via: project-memory log --todo "description" -->',
  '<!-- Collapsed summaries of past completed tasks (auto-generated by prune) -->',
]);

function ensureMemoryFiles() {
  if (!fs.existsSync(memoryDir)) {
    fs.mkdirSync(memoryDir, { recursive: true });
  }

  if (!fs.existsSync(contextPath)) {
    throw new Error(`Missing memory context file at ${contextPath}`);
  }

  if (!fs.existsSync(statePath)) {
    const initialState = {
      version: 1,
      createdAt: new Date().toISOString(),
      lastUpdated: new Date().toISOString(),
      entryCount: 0,
      projectName: path.basename(repoRoot),
    };
    fs.writeFileSync(statePath, `${JSON.stringify(initialState, null, 2)}\n`, 'utf8');
  }
}

function loadContextLines() {
  return fs.readFileSync(contextPath, 'utf8').replace(/\r\n/g, '\n').split('\n');
}

function saveContextLines(lines) {
  fs.writeFileSync(contextPath, `${lines.join('\n').trimEnd()}\n`, 'utf8');
}

function loadState() {
  return JSON.parse(fs.readFileSync(statePath, 'utf8'));
}

function saveState(state) {
  fs.writeFileSync(statePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8');
}

function touchState() {
  const state = loadState();
  state.lastUpdated = new Date().toISOString();
  state.entryCount = Number(state.entryCount || 0) + 1;
  saveState(state);
}

function sectionRange(lines, header) {
  const start = lines.findIndex((line) => line.trim() === header);
  if (start === -1) {
    throw new Error(`Section not found: ${header}`);
  }

  let end = lines.length;
  for (let i = start + 1; i < lines.length; i += 1) {
    if (lines[i].startsWith('## ')) {
      end = i;
      break;
    }
  }

  return { start, end };
}

function appendBullet(lines, header, message) {
  const { start, end } = sectionRange(lines, header);
  const sectionBody = lines.slice(start + 1, end);
  const cleanedBody = sectionBody.filter((line) => !PLACEHOLDER_LINES.has(line.trim()));
  const bullet = `- ${message.trim()}`;

  if (cleanedBody.some((line) => line.trim() === bullet)) {
    return false;
  }

  let insertAt = end;
  while (insertAt > start + 1 && lines[insertAt - 1].trim() === '') {
    insertAt -= 1;
  }

  const hasRealContent = cleanedBody.some((line) => line.trim() !== '' && !line.trim().startsWith('>'));

  if (!hasRealContent) {
    const filtered = [];
    for (let i = start + 1; i < end; i += 1) {
      const trimmed = lines[i].trim();
      if (!PLACEHOLDER_LINES.has(trimmed)) {
        filtered.push(lines[i]);
      }
    }

    lines.splice(start + 1, end - (start + 1), ...filtered);
    const freshRange = sectionRange(lines, header);
    insertAt = freshRange.end;
    while (insertAt > freshRange.start + 1 && lines[insertAt - 1].trim() === '') {
      insertAt -= 1;
    }
  }

  lines.splice(insertAt, 0, bullet);
  return true;
}

function pruneCompleted(lines) {
  const completedRange = sectionRange(lines, SECTION_HEADERS.completed);
  const historyRange = sectionRange(lines, SECTION_HEADERS.history);

  const completedItems = lines
    .slice(completedRange.start + 1, completedRange.end)
    .filter((line) => line.trim().startsWith('- '));

  if (completedItems.length <= 12) {
    return false;
  }

  const keep = completedItems.slice(0, 8);
  const archive = completedItems.slice(8);

  const newCompletedBody = ['', ...keep, ''];
  lines.splice(
    completedRange.start + 1,
    completedRange.end - completedRange.start - 1,
    ...newCompletedBody
  );

  const refreshedHistory = sectionRange(lines, SECTION_HEADERS.history);
  const insertAt = refreshedHistory.start + 1;
  const summaryLines = [
    '',
    `- Pruned ${archive.length} completed task${archive.length === 1 ? '' : 's'} on ${new Date().toISOString().slice(0, 10)}:`,
    ...archive.map((line) => `  ${line.trim()}`),
  ];

  lines.splice(insertAt, 0, ...summaryLines);
  return true;
}

function parseLogArgs(args) {
  const flags = ['--decision', '--mistake', '--todo', '--completed'];

  for (const flag of flags) {
    const index = args.indexOf(flag);
    if (index !== -1 && args[index + 1]) {
      return { flag, value: args[index + 1] };
    }
  }

  throw new Error('Usage: node scripts/project-memory.js log --decision|--mistake|--todo|--completed "message"');
}

function handleRead() {
  process.stdout.write(fs.readFileSync(contextPath, 'utf8'));
}

function handleLog(args) {
  const { flag, value } = parseLogArgs(args);
  const lines = loadContextLines();

  const headerByFlag = {
    '--decision': SECTION_HEADERS.decisions,
    '--mistake': SECTION_HEADERS.mistakes,
    '--todo': SECTION_HEADERS.todos,
    '--completed': SECTION_HEADERS.completed,
  };

  const inserted = appendBullet(lines, headerByFlag[flag], value);
  if (!inserted) {
    console.log('Entry already exists. No changes made.');
    return;
  }

  saveContextLines(lines);
  touchState();
  console.log(`Logged ${flag.replace('--', '')}: ${value}`);
}

function handlePrune() {
  const lines = loadContextLines();
  const changed = pruneCompleted(lines);

  if (!changed) {
    console.log('No prune needed.');
    return;
  }

  saveContextLines(lines);
  touchState();
  console.log('Pruned completed tasks into history.');
}

function handleHelp() {
  console.log('project-memory local CLI');
  console.log('');
  console.log('Usage:');
  console.log('  node scripts/project-memory.js read');
  console.log('  node scripts/project-memory.js log --decision "message"');
  console.log('  node scripts/project-memory.js log --mistake "message"');
  console.log('  node scripts/project-memory.js log --todo "message"');
  console.log('  node scripts/project-memory.js log --completed "message"');
  console.log('  node scripts/project-memory.js prune');
}

function main() {
  ensureMemoryFiles();

  const [, , command, ...args] = process.argv;

  switch (command) {
    case 'read':
      handleRead();
      break;
    case 'log':
      handleLog(args);
      break;
    case 'prune':
      handlePrune();
      break;
    case 'help':
    case '--help':
    case '-h':
    case undefined:
      handleHelp();
      break;
    default:
      throw new Error(`Unknown command: ${command}`);
  }
}

try {
  main();
} catch (error) {
  console.error(`project-memory error: ${error.message}`);
  process.exit(1);
}
